/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.miui.tsmclient.ui.quick;

import miui.app.Activity;
import android.graphics.Bitmap;
import android.content.Intent;
import com.miui.tsmclient.util.LogUtils;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.net.Uri;
import android.os.Bundle;
import android.view.Window;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.BitmapDrawable;
import android.content.res.Resources;
import com.miui.tsmclient.util.UiUtils;
import android.app.Fragment;

public class DoubleClickActivity extends Activity {
    private static final String ACTION_DOUBLE_CLICK = "com.miui.intent.action.DOUBLE_CLICK";
    public static final String EVENT_SOURCE_KEY_RF_ON = "key_rf_on";
    public static final String EVENT_SOURCE_KEY_VOLUME_DOWN = "key_volume_down";
    public static final String KEY_EVENT_SOURCE = "event_source";
    public static final int REQUEST_OPEN_BANKCARD = 0x1;
    private SwitchCardFragment mSwitchCardFragment;
    private Bitmap mWindowBg;
    
    protected void onCreate(Bundle p1) {
        requestWindowFeature(0x9);
        super.onCreate(p1);
        getWindow().addFlags(0x280080);
        Drawable "wallpaper" = getWallpaper();
        Bitmap "srcBm" = (BitmapDrawable)"wallpaper".getBitmap().copy(Bitmap.Config.ARGB_4444, true);
        mWindowBg = maskBitmap("srcBm");
        getWindow().setBackgroundDrawable(new BitmapDrawable(getResources(), mWindowBg));
        "srcBm".recycle();
        mSwitchCardFragment = new SwitchCardFragment();
        mSwitchCardFragment.setAttachedActivitySource(getCalledSource(getIntent()));
        UiUtils.replaceFragment(this, mSwitchCardFragment);
    }
    
    protected void onNewIntent(Intent p1) {
        super.onNewIntent(p1);
        mSwitchCardFragment.setAttachedActivitySource(getCalledSource(p1));
    }
    
    private String getCalledSource(Intent p1) {
        if(p1 != null) {
            String "calledSource" = p1.getStringExtra("event_source");
            LogUtils.i("event_source: " + "calledSource");
            return "calledSource";
        }
        return null;
    }
    
    private Bitmap maskBitmap(Bitmap p1) {
        if(p1 == null) {
            return null;
        }
        Bitmap "newBitmap" = Bitmap.createBitmap(p1);
        Canvas "canvas" = new Canvas("newBitmap");
        Paint "paint" = new Paint();
        "paint".setColor(0x0);
        "paint".setAlpha(0xdc);
        "canvas".drawRect(0.0f, 0.0f, (float)p1.getWidth(), (float)p1.getHeight(), "paint");
        "canvas".save(0x1f);
        "canvas".restore();
        return "newBitmap";
    }
    
    protected void onDestroy() {
        if(mWindowBg != null) {
            mWindowBg.recycle();
        }
        super.onDestroy();
    }
    
    protected void onActivityResult(int p1, int p2, Intent p3) {
        super.onActivityResult(p1, p2, p3);
        if(0x1 == p1) {
            if(p2 == -0x1) {
                Intent "intent" = new Intent("android.intent.action.VIEW");
                "intent".setPackage("com.mipay.wallet");
                "intent".setData(Uri.parse("https://app.mipay.com?id=mipay.home"));
                startActivity("intent");
                finish();
            }
        }
    }
}
